name: mysite2
on: 
  push:
    branches: ["dev"]
    paths:
    - 'html/**'
  pull_request:
    types: [opened]
    branches: 
      - 'release'

env:
  owner: dadapapa

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: cache css and images
        uses: actions/cache@v3
        with:
          path: |
            html/styles
            html/images
          key: ${{ runner.os }}-assets-${{ hashFiles('html/styles/**','html/images/**')}}
          restore-keys: |
            ${{ runner.os}}-assets-
 
  dockerizing:
    needs:
      - website
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.owner}}/myweb:1.0